name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: npm install --legacy-peer-deps && npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
